### ISSUE TITLE
english or german

### ISSUE THREAD

**Issue by brianteeman** [joomla/test-system#21]
any chance of the code on the home page being in english and not german?

**Comment by nibra** [comment]
Which code on which homepage?

**Comment by brianteeman** [comment]
the homepage of this repo
readme.md

**Comment by nibra** [comment]
Ah ok, so you're talking about the sample `git` output.
You can just follow the instructions and paste the output of _your_ localised `git` into a PR.

**Comment by brianteeman** [comment]
i could but that would assume i know what i am doing and as i dont understand german....

**Comment by puneet0191** [comment]
Agree I will update that, thanks :+1:

**Comment by brianteeman** [comment]
Thank you @puneet0191

**Comment by dneukirchen** [comment]
Thx
